export enum NotesActionTypes {
    FETCH_NOTES = 'FETCH_NOTES',
    CREATE_NOTE = 'CREATE_NOTE',
    GET_NOTES = 'GET_NOTES',
    VIEW_NOTE = 'VIEW_NOTE',
    UPDATE_NOTE = 'UPDATE_NOTE',
    DELETE_NOTE = 'DELETE_NOTE'
  }
  